version: "3"
services:
  pg:
    image: postgres:latest
    restart: always
    container_name: pg
    environment:
      POSTGRES_USER: XML
      POSTGRES_PASSWORD: ftn
      POSTGRES_DB: XML_TEST
    ports:
      - "4003:5432"
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U XML -d "XML_TEST"']
      interval: 5s
      timeout: 5s
      retries: 5
